schema: "https://api.thegraph.com/subgraphs/name/amxx/access-control"
documents: "src/**/*.graphql"
overwrite: true
generates:
  src/lib/subgraph/queries.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typed-document-node"
    config:
      useTypeImports: true
  src/lib/subgraph/schema.json:
    plugins:
      - "introspection"
